version: 1
llm:
  active_provider: azure_ai_foundry
  active_model_id: gpt_5_4_nano::gpt-5.4-nano
  providers:
    ollama:
      refresh_models_on_startup: false
      models:
      - id: gemma4:e4b
        display_name: gemma4:e4b
        role: primary
        enabled: true
      - id: gemma4:e2b
        display_name: gemma4:e2b
        role: secondary
        enabled: true
      - id: gemma4:31b-cloud
        display_name: gemma4:31b-cloud
        role: secondary
        enabled: true
      - id: gpt-oss:120b-cloud
        display_name: gpt-oss:120b-cloud
        role: secondary
        enabled: true
    lm_studio:
      refresh_models_on_startup: false
      models: []
    azure_ai_foundry:
      refresh_models_on_startup: false
      models:
      - id: 4o_mini::4o-mini
        display_name: 4o-mini [4o_mini]
        role: primary
        enabled: true
      - id: oss120b::oss120b
        display_name: oss120b [oss120b]
        role: secondary
        enabled: true
      - id: primary::gpt-4o-mini
        display_name: gpt-4o-mini [primary]
        role: secondary
        enabled: true
      - id: secondary::gpt-4.1-mini
        display_name: oss120b [secondary]
        role: secondary
        enabled: true
      - id: llama_70b::Llama-3.3-70B-Instruct
        display_name: LLAMA 70b [llama_70b]
        role: secondary
        enabled: true
      - id: gpt_5_4_nano::gpt-5.4-nano
        display_name: gpt-5.4-nano [gpt_5_4_nano]
        role: secondary
        enabled: true
runtime:
  llm:
    max_passes: 1
    max_concurrent_requests: 20
  files:
    max_parallel_files: 2
